### PR TITLE
Review and fix Media Shuttle Webtoken Transfers

### PR DESCRIPTION
**Pull request by sheetalkadwal**
**Trello Card:** https://trello.com/c/ogpSN1kW/3-review-and-fix-media-shuttle-webtoken-transfers

**Commit Summary:**

3f3c9a1: Fixed dependencies and issues in App.js
3bf9b0f: Updated dependency version and console warnings
e10a70d: Removed the file which was checked in by mistake

### CODE REVIEW

**Comment by sheetalkadwal** [comment]
Hi @tobsign, I am left with a few last sets of warnings given below which are internal dependencies for "react-scripts" and "node-sass". Both "react-scripts" and "node-sass" are at latest version, seems like internal dependencies are deprecated which gives warnings on npm install. Could you please take a look and suggest how should we proceed on these.

1. npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
2. npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
3. npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
4. npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
5. npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
6. npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

**Comment by tobsign** [comment]
I don't think these warnings are really blocking, but you may want to solve them by overriding some of the dependencies imports, eg, add to package.json a section like
```
  "overrides": {
    "node-sass": {
      "node-gyp": "^9.3.1",
      "make-fetch-happen": "^11.0.3"
    }
  },
```

**Review by tobsign — APPROVED** [review]
lgtm

**Comment by sheetalkadwal** [comment]
> I don't think these warnings are really blocking, but you may want to solve them by overriding some of the dependencies imports, eg, add to package.json a section like
> 
> ```
>   "overrides": {
>     "node-sass": {
>       "node-gyp": "^9.3.1",
>       "make-fetch-happen": "^11.0.3"
>     }
>   },
> ```

Sure, will look into this.

**Pull request merged**
